server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 112885
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.153.129
    port: 6379
    password: 112885

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  typeAliasesPackage: com.htl.cloudmemory.entity
  mapperLocations: classpath:mapper/*.xml