package com.htl.cloudmemory.entity;

public class GItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.id
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemName
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    private String itemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemPrice
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    private String itemprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.id
     *
     * @return the value of items.id
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.id
     *
     * @param id the value for items.id
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemName
     *
     * @return the value of items.itemName
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemName
     *
     * @param itemname the value for items.itemName
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemPrice
     *
     * @return the value of items.itemPrice
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    public String getItemprice() {
        return itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemPrice
     *
     * @param itemprice the value for items.itemPrice
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    public void setItemprice(String itemprice) {
        this.itemprice = itemprice == null ? null : itemprice.trim();
    }
}