package com.htl.cloudmemory.dao;

import com.htl.cloudmemory.entity.GUser;
import java.util.List;

public interface GUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    int insert(GUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    GUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    List<GUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Dec 11 17:21:27 CST 2018
     */
    int updateByPrimaryKey(GUser record);
}